version: "3.6"

#docker run -i --rm -p 7080:8080 --name video-analytics-serving-gstreamer video-analytics-serving-gstreamer

services:
  video-analytics-serving:
    container_name: video-analytics-serving
    image: video-analytics-serving-${FRAMEWORK}
    network_mode: host
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - /tmp:/tmp
      - /dev:/dev
      - ${SOURCE_DIR}/samples:/home/video-analytics-serving/samples
      - ${SOURCE_DIR}/edgex:/home/video-analytics-serving/edgex
#      - ${SOURCE_DIR}/models:/home/video-analytics-serving/models 
#      - ${SOURCE_DIR}/pipelines/gstreamer:/home/video-analytics-serving/pipelines
